config/routes.rb
Rails.application.routes.draw do
  resources :policies

  root 'policies#index'

end

app/models/policy.rb
class Policy < ActiveRecord::Base
 validates :number, uniqueness: {scope: :program}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  # GET /policies
  # GET /policies.json
  def index
    if params[:number]
      @policies = Policy.where(number: params[:number])
      if params[:date]
        @policies = @policies.where("date(insurance_started_at)  <= ?", params[:date].to_date).where("date(insurance_finished_at) >= ?", params[:date].to_date)
      end
    else
      @policies = Policy.all
    end
  end

  # GET /policies/1
  # GET /policies/1.json
  def show

  end

  # GET /policies/new
  def new
    @policy = Policy.new
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(policy_params)

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: 'Policy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:name,:program,:orgin,:number,:insurance_started_at,:insurance_finished_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apipolicy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/policies/_form.html.erb
<%= form_for(@policy) do |f| %>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
    <%= f.label :program %><br>
    <%= f.text_field :program %>
  </div>
  <div class="field">
    <%= f.label "od" %><br>
    <%= f.text_field :insurance_started_at %>
  </div>
  <div class="field">
    <%= f.label "do" %><br>
    <%= f.text_field :insurance_finished_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/policies/edit.html.erb
<h1>Editing Policy</h1>

<%= render 'form' %>

<%= link_to 'Show', @policy %> |
<%= link_to 'Back', policies_path %>

app/views/policies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Policies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Orgin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= policy.name %></td>
        <td><%= policy.number %></td>
        <td><%= link_to 'Show', policy %></td>
        <td><%= link_to 'Edit', edit_policy_path(policy) %></td>
        <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Policy', new_policy_path %>

app/views/policies/new.html.erb
<h1>New Policy</h1>

<%= render 'form' %>

<%= link_to 'Back', policies_path %>

app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @policy.name %>
</p>

<p>
  <strong>number:</strong>
  <%= @policy.number %>
</p>

<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>